<?php
namespace modava\faq\components;

use backend\components\MyController;

class MyFaqController extends MyController
{
    public function behaviors()
    {
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }
}
